# Generated by Django 4.0 on 2023-09-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=100)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('agency_name', models.CharField(max_length=100)),
            ],
        ),
    ]
