# Generated by Django 4.0 on 2023-09-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='video_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
